# Generated by Django 4.0.3 on 2022-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
