# Generated by Django 4.0.3 on 2022-03-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='text',
        ),
    ]
